[package]
name = "wallpaper-updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.1"
clap_derive = "4.4.0"
config = "0.13.3"
home = "0.5.5"
rand = "0.8.5"
serde = "1.0.188"
serde_derive = "1.0.188"

[lib]
src = "src/lib.rs"
